# 아래 client-id와 client-secret은 예시로 넣은 더미데이터입니다. 참고만 부탁드려요.
spring:
  h2:
    console:
      enabled: true
      path: /console
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 868894287309-nqeabavsr1nphhcsvsgmhn671skld4rk.apps.googleusercontent.com
            client-secret: Kgfw4eUpjS122FSMAXTK-D3A
          facebook:
            client-id: 11612612521462
            client-secret: 6578235217c5c365a98c51b02d0308ac
custom:
  oauth2:
    kakao:
      client-id: 6657c6a41d2b71a224497899219c1bcb
      client-secret: LoEW701cml6jWzrmwlJ5zTJecUNoqX0P
    naver:
      client-id: ecZewu7LQgJtTkmRDbdQ
      client-secret: pfJboVunvL